### ISSUE TITLE
Single-contract mode doesn't work anymore

### ISSUE THREAD

**Issue by jubnzv** [nowarp/misti#233]
```
$ ts-node src/main.ts test/detectors/SendInLoop.tact
Compilation error: Could not find entrypoint test/detectors/SendInLoop.tact
error Command failed with exit code 1.
```

Was broken in #231
